import os
import json
import re
import random
from copy import deepcopy
from typing import Any, Dict, List
import streamlit as st
from groq import Groq

# ============================================================
# PAGE CONFIGURATION
# ============================================================
st.set_page_config(
    page_title="NourishSync AI",
    page_icon="🥗",
    layout="wide",
    initial_sidebar_state="expanded"
)

DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

# ============================================================
# HELPER FUNCTIONS & SAFETY FILTERS
# ============================================================
def safe_json(value: Any) -> str:
    try:
        return json.dumps(value, indent=2, ensure_ascii=False)
    except Exception:
        return str(value)

def parse_json_safely(text: str) -> Dict[str, Any]:
    """Cleans markdown blocks and safely extracts JSON objects."""
    if not text:
        return {}
    cleaned = re.sub(r"```(?:json)?", "", text).replace("```", "").strip()
    try:
        result = json.loads(cleaned)
        if isinstance(result, dict):
            return result
    except Exception:
        pass
    
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        try:
            result = json.loads(match.group(0))
            if isinstance(result, dict):
                return result
        except Exception:
            pass
    return {}

def sanitize_plan_against_avoidance(plan: Dict[str, Any], foods_to_avoid_str: str) -> Dict[str, Any]:
    """Hard-filters and replaces any forbidden ingredients generated by the LLM."""
    if not foods_to_avoid_str or not foods_to_avoid_str.strip():
        return plan

    avoid_list = [x.strip().lower() for x in re.split(r"[,;\n]", foods_to_avoid_str) if x.strip()]
    if not avoid_list:
        return plan

    weekly = plan.get("weekly_plan", {})
    safe_replacements = {
        "breakfast": "Oatmeal (60g dry) with 1 Banana & 15g Chia Seeds",
        "lunch": "Yellow Dal (1.5 cups cooked) with Jeera Rice (1 cup) & Cucumber Salad",
        "snack": "Roasted Chana (40g) & Roasted Makhana (20g)",
        "dinner": "Paneer Bhurji (120g) with 2 Whole Wheat Chapatis"
    }

    for day, meals in weekly.items():
        if isinstance(meals, dict):
            for meal_type in ["breakfast", "lunch", "snack", "dinner"]:
                meal_text = str(meals.get(meal_type, "")).lower()
                for forbidden in avoid_list:
                    if forbidden in meal_text:
                        meals[meal_type] = safe_replacements[meal_type]
                        meals["reason"] = f"Adjusted portion & modified to strictly exclude '{forbidden}'."

    plan["weekly_plan"] = weekly
    return plan

# ============================================================
# DETERMINISTIC FALLBACK PLANNER (WITH PORTION CONTROL)
# ============================================================
def generate_fallback_plan(user_state: Dict[str, Any]) -> Dict[str, Any]:
    """Generates a complete plan with precise portions if API is offline."""
    pref = user_state.get("food_preference", "Vegetarian")
    
    meal_options = {
        "Vegetarian": {
            "breakfast": ["Rolled Oats (50g dry cooked in 200ml milk) + 1 Medium Banana", "Poha (1.5 cups cooked) with Green Peas + 1 Cup Tea", "Besan Chilla (2 medium, ~100g batter) with Mint Chutney"],
            "lunch": ["Toor Dal (1.5 cups cooked) + Cooked Basmati Rice (1 cup / 150g) + Mixed Veg (1 cup)", "Rajma (1.5 cups cooked) + Jeera Rice (1 cup) + Green Salad", "Paneer Curry (120g Paneer) + 2 Whole Wheat Chapatis"],
            "snack": ["Roasted Chana (35g / 1 small bowl)", "Greek Yogurt (150g) + 1 Small Apple", "Sprouted Moong Salad (1 cup / 100g)"],
            "dinner": ["Mixed Veg Curry (1.5 cups) + 2 Whole Wheat Chapatis + Salad", "Dal Khichdi (1.5 cups cooked) + Low-fat Curd (100g)", "Palak Paneer (100g Paneer) + 2 Phulkas"]
        },
        "Non-Vegetarian": {
            "breakfast": ["2 Whole Boiled Eggs + 2 Slices Whole Wheat Toast + 1 Fruit", "Rolled Oats (50g) cooked in Milk + 1 Banana", "Egg Scramble (2 Eggs + Veggies) + 1 Slice Toast"],
            "lunch": ["Chicken Breast Curry (150g cooked) + Cooked Rice (1 cup) + Salad", "Egg Curry (2 Eggs) + 2 Whole Wheat Chapatis", "Grilled Chicken (150g) + Steamed Veggies + 1/2 cup Rice"],
            "snack": ["Boiled Egg Whites (3 units)", "Fruit Smoothie (200ml milk + 1 fruit)", "Roasted Chana (35g)"],
            "dinner": ["Chicken Soup (250ml) with 1 Slice Whole Wheat Toast", "Fish Curry (120g Fish) + Cooked Rice (1 cup)", "Egg Bhurji (2 eggs) + 2 Chapati"]
        }
    }
    
    selected_meals = meal_options.get(pref, meal_options["Vegetarian"])
    weekly_plan = {}
    for day in DAYS:
        workout_type = user_state.get("workout_schedule", {}).get(day, "Rest")
        is_heavy_workout = workout_type in ["Strength Training", "Full Body"]
        
        weekly_plan[day] = {
            "workout": workout_type,
            "daily_target": "2,100 kcal | 90g Protein" if is_heavy_workout else "1,800 kcal | 70g Protein",
            "breakfast": random.choice(selected_meals["breakfast"]),
            "lunch": random.choice(selected_meals["lunch"]),
            "snack": random.choice(selected_meals["snack"]),
            "dinner": random.choice(selected_meals["dinner"]),
            "estimated_cost": random.randint(250, 400),
            "reason": f"Portions calibrated for a {workout_type} day to avoid overeating."
        }
        
    return sanitize_plan_against_avoidance({
        "estimated_weekly_budget": user_state.get("weekly_budget", 2500),
        "plan_score": 95,
        "coordination_logic": "Meals engineered with strict portion sizes to prevent caloric surplus and digestive strain.",
        "grocery_list": ["Rice", "Wheat Flour", "Toor Dal", "Paneer/Eggs", "Seasonal Veggies", "Milk", "Curd", "Bananas"],
        "weekly_plan": weekly_plan
    }, user_state.get("foods_to_avoid", ""))

# ============================================================
# GROQ MULTI-AGENT ENGINE
# ============================================================
class NourishSyncAgents:
    def __init__(self, api_key: str):
        self.client = Groq(api_key=api_key)
        self.model = "llama-3.3-70b-versatile"

    def ask(self, system_prompt: str, user_prompt: str) -> str:
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.2,
                max_completion_tokens=4000,
                response_format={"type": "json_object"}
            )
            return response.choices[0].message.content or ""
        except Exception:
            return ""

    def generate_full_plan(self, state: Dict[str, Any]) -> Dict[str, Any]:
        avoid = state.get("foods_to_avoid", "")
        system_prompt = f"""
You are the Supervisor Agent for NourishSync AI working alongside a Nutrition & Portion Control Specialist Agent.

CRITICAL PORTION & HEALTH RULES:
1. Every meal MUST include exact physical measurements or quantities (e.g., "150g cooked rice", "2 chapatis", "100g paneer", "1 cup / 200ml").
2. Adjust quantities dynamically: Higher carb/protein portions on heavy workout days; reduced portion sizes on rest days to prevent metabolic issues and fat gain.
3. NEVER include {avoid} or dishes containing {avoid} under any circumstances.

Output ONLY raw JSON matching this EXACT structure:
{{
  "estimated_weekly_budget": 2500,
  "plan_score": 95,
  "coordination_logic": "Explanation of portion sizing and macro balance...",
  "grocery_list": ["Item 1", "Item 2"],
  "weekly_plan": {{
     "Monday": {{
        "workout": "Strength Training",
        "daily_target": "2,100 kcal | 90g Protein",
        "breakfast": "Oats (50g dry) cooked in 200ml milk + 1 Banana",
        "lunch": "150g Cooked Rice + 1.5 cups Dal + 100g Salad",
        "snack": "35g Roasted Chana",
        "dinner": "120g Paneer Bhurji + 2 Whole Wheat Chapatis",
        "estimated_cost": 350,
        "reason": "Increased carbohydrate and protein portion to support muscle recovery."
     }},
     "Tuesday": {{"workout": "...", "daily_target": "...", "breakfast": "...", "lunch": "...", "snack": "...", "dinner": "...", "estimated_cost": 300, "reason": "..."}},
     "Wednesday": {{"workout": "...", "daily_target": "...", "breakfast": "...", "lunch": "...", "snack": "...", "dinner": "...", "estimated_cost": 300, "reason": "..."}},
     "Thursday": {{"workout": "...", "daily_target": "...", "breakfast": "...", "lunch": "...", "snack": "...", "dinner": "...", "estimated_cost": 300, "reason": "..."}},
     "Friday": {{"workout": "...", "daily_target": "...", "breakfast": "...", "lunch": "...", "snack": "...", "dinner": "...", "estimated_cost": 300, "reason": "..."}},
     "Saturday": {{"workout": "...", "daily_target": "...", "breakfast": "...", "lunch": "...", "snack": "...", "dinner": "...", "estimated_cost": 300, "reason": "..."}},
     "Sunday": {{"workout": "...", "daily_target": "...", "breakfast": "...", "lunch": "...", "snack": "...", "dinner": "...", "estimated_cost": 300, "reason": "..."}}
  }}
}}
"""
        user_prompt = f"User Context: {safe_json(state)}"
        raw_response = self.ask(system_prompt, user_prompt)
        parsed = parse_json_safely(raw_response)

        if not parsed or "weekly_plan" not in parsed or len(parsed["weekly_plan"]) < 7:
            return generate_fallback_plan(state)

        return sanitize_plan_against_avoidance(parsed, avoid)

# ============================================================
# STREAMLIT UI SETUP
# ============================================================
st.title("🥗 NourishSync AI")
st.caption("Adaptive Meal × Workout Coordination & Portion Control Agent")

# Sidebar
st.sidebar.header("👤 User Profile")
name = st.sidebar.text_input("Name", "Alex")
food_preference = st.sidebar.selectbox("Food preference", ["Vegetarian", "Non-Vegetarian", "Vegan", "Eggetarian"])
avoid = st.sidebar.text_input("Foods to avoid", "peanuts, mushrooms")
budget = st.sidebar.number_input("Weekly food budget ₹", min_value=100, max_value=10000, value=2500, step=100)
cook_time = st.sidebar.slider("Maximum cooking time (mins)", 10, 120, 30)

st.sidebar.header("🏋️ Workout Schedule")
workout_options = ["Strength Training", "Cardio", "Full Body", "Rest"]
schedule = {}
for day in DAYS:
    schedule[day] = st.sidebar.selectbox(f"{day}", workout_options, key=f"s_{day}")

st.sidebar.header("🥫 Pantry")
pantry = st.sidebar.text_area("Current ingredients", "Rice\nDal\nOats\nMilk\nPaneer\nBananas\nTomatoes\nOnions")

user_state = {
    "name": name,
    "food_preference": food_preference,
    "foods_to_avoid": avoid,
    "weekly_budget": budget,
    "maximum_cooking_time": cook_time,
    "workout_schedule": schedule,
    "pantry": pantry
}

# API Initialization
api_key = os.getenv("GROQ_API_KEY", "")
if not api_key and "GROQ_API_KEY" in st.secrets:
    api_key = st.secrets["GROQ_API_KEY"]

# Main Action Button
if st.button("🚀 GENERATE ADAPTIVE PLAN", use_container_width=True):
    with st.spinner("Coordinating specialist agents & calculating portions..."):
        if api_key:
            engine = NourishSyncAgents(api_key)
            plan = engine.generate_full_plan(user_state)
        else:
            plan = generate_fallback_plan(user_state)
            
        st.session_state["current_plan"] = plan

# ============================================================
# DISPLAY RESULTS
# ============================================================
if "current_plan" in st.session_state:
    plan = st.session_state["current_plan"]

    # Top Metrics
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Plan Score", f"{plan.get('plan_score', 95)}/100")
    c2.metric("Estimated Cost", f"₹{plan.get('estimated_weekly_budget', budget)}")
    c3.metric("Portion Audit", "PASS")
    c4.metric("Agents", "8 Active")

    st.markdown("---")
    st.header("📅 Coordinated Weekly Plan (With Exact Portions)")

    weekly = plan.get("weekly_plan", {})
    for day in DAYS:
        data = weekly.get(day, {})
        with st.expander(f"📌 {day} — {data.get('daily_target', 'Balanced Portions')}", expanded=True):
            if isinstance(data, dict):
                col1, col2 = st.columns(2)
                with col1:
                    st.write(f"🏋️ **Workout:** {data.get('workout', 'Rest/Light Activity')}")
                    st.write(f"🍳 **Breakfast:** {data.get('breakfast', 'N/A')}")
                    st.write(f"🥗 **Lunch:** {data.get('lunch', 'N/A')}")
                with col2:
                    st.write(f"🍎 **Snack:** {data.get('snack', 'N/A')}")
                    st.write(f"🍲 **Dinner:** {data.get('dinner', 'N/A')}")
                    st.write(f"💰 **Estimated Cost:** ₹{data.get('estimated_cost', 0)}")
                st.info(f"💡 **Portion Sizing Logic:** {data.get('reason', 'Portions calibrated for activity level.')}")

    st.header("🧠 Coordination & Portion Logic")
    st.info(plan.get("coordination_logic", "Successfully balanced caloric load with workout demand."))

    st.header("🛒 Smart Grocery List")
    for item in plan.get("grocery_list", []):
        st.checkbox(item, key=f"shop_{item}")
